---
title: "Northern Estuaries"
format:
  html:
    toc: true
    dev: png
    type: cairo
encoding: UTF-8
knitr:
  opts_chunk:
    echo: false
    message: false
    warning: false
editor_options: 
  chunk_output_type: console
execute: 
  freeze: true
---

```{r date,echo=FALSE,message=FALSE,warning=FALSE}
up.date <- format(Sys.time(),tz="America/New_York",usetz=T,"%F %R")
up.date <- as.POSIXct(up.date,tz="America/New_York")

dst.check=c(NA,FALSE,TRUE)[as.POSIXlt(up.date)$isdst+2]# from lubridate::dst(...) code
```

```{r setup and data}

library(AnalystHelper)
library(reshape2)
library(plyr)
library(sf)
library(EVERSpatDat)
library(mapmisc)
library(flextable)
library(tmap)

library(ggplot2)
theme_set(theme_minimal(base_size = 16)+#,base_family = "serif")+
            theme_bw()+
            theme(panel.border = element_rect("black",fill=NA,linewidth=1)))

utm17<-st_crs("EPSG:26917");# CRS for NAD83 UTM17

tmap_mode("view")
# Functions  ----------------------------------------------------------------
heck_nice <- function(x,round){
      e <- floor(log10(x))
    f <- x/(10^e)
    if (round) {
        if (f < 1.5) 
            nf <- 1
        else if (f < 3) 
            nf <- 2
        else if (f < 7) 
            nf <- 5
        else nf <- 10
    }
    else {
        if (f <= 1) 
            nf <- 1
        else if (f <= 2) 
            nf <- 2
        else if (f <= 5) 
            nf <- 5
        else nf <- 10
    }
    nf * (10^e)
}
heckbert_labs <- function(dmin,dmax,m){
  
    range <- heck_nice((dmax - dmin), FALSE)
    lstep <- heck_nice(range/(m - 1), TRUE)
    lmin <- floor(dmin/lstep) * lstep
    lmax <- ceiling(dmax/lstep) * lstep
    seq(lmin, lmax, by = lstep)
}
# Dates ------------------------------------------------------------------
CurWY      <- WY(date.fun(Sys.time()))
Start.Date <- date.fun(paste(CurWY - 4, "05-01", sep = "-"))
End.Date   <- date.fun(Sys.Date() - 1)
YEST       <- End.Date
dates      <- c(Start.Date, End.Date)
flab.dates <- c(date.fun(paste(CurWY - 15, "05-01", sep = "-")), End.Date)
LOK.sdate  <- date.fun("2007-05-01")

# Plotting constants/colors --------------------------------------------
lok_stage_yrs <- c(CurWY-3,CurWY-2, CurWY-1, CurWY)
lok_stage_cols <- c(adjustcolor(c("purple","forestgreen","blue"), 0.5), "red")

stage_yrs <- c(CurWY-2, CurWY-1, CurWY)
stage_cols <- c(adjustcolor(c("forestgreen","blue"), 0.5), "red")

Q_cols <- c("dodgerblue1","indianred1","forestgreen")
```

*Page rendered: `r format(Sys.time(), "%b %d, %Y %H:%M %Z")` &nbsp;•&nbsp; Data through: `r format(YEST, "%b %d, %Y")`*

**Work in progress**

```{r test, dpi=96,fig.width=6.5,fig.height=4.5}
plot(rnorn(100))
```