name: Render and Deploy Quarto Site

on:
  push:
  schedule:
  # Runs every day at 12:30 AM UTC (0830 EST)
    - cron: "30 12 * * *"

permissions:
  contents: write  # allows committing rendered files
  
jobs:
  render:
    name: Render report
    runs-on: windows-latest
    env:
      R_LIBS_USER: ${{ github.workspace }}/.Rlibrary
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
          r-version: '4.2.0' 
          
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-R-${{ hashFiles('**/*.R', '**/*.Rmd') }}
        restore-keys: |
          ${{ runner.os }}-R-

    - name: Install R packages (CRAN + GitHub)
      shell: Rscript {0}
      run: |
        install.packages(c("remotes","reshape2","plyr","zoo",
        "RcppRoll","dataRetrieval","downloadthis","rvest","httr",
        "mapmisc","future","future.apply","flextable","ggplot2"))

        remotes::install_github("SwampThingPaul/AnalystHelper")
        remotes::install_github("SwampThingPaul/EVERSpatDat")
        install.packages('sf', type = "binary")
        install.packages('terra', repos = c('https://rspatial.r-universe.dev', 'https://cloud.r-project.org'))
        install.packages('raster', repos = c('https://rspatial.r-universe.dev', 'https://cloud.r-project.org'))

    - name: Render Quarto project
      run: quarto render
        
    - name: Commit and push changes
      run: |
        git config user.name "SwampThingPaul"
        git config user.email "<>"
        git add -A 
        git commit -m 'update report' || echo "No changes to commit"
        git pull --rebase origin master # git pull --ff-only
        git push origin || echo "No changes to commit"
          
    - name: Publish Quarto site to GitHub Pages
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages